---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "people-config-e4n3"
  namespace: "default"
  labels:
    app: "people"
data:
  GOOGLE_CLOUD_PROJECT: "people-ae72e"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "people"
  namespace: "default"
  labels:
    app: "people"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "people"
  template:
    metadata:
      labels:
        app: "people"
    spec:
      containers:
      - name: "23people-1"
        image: "gcr.io/people-ae72e/github.com/inalef/23people:$SHORT_SHA"
        env:
        - name: "GOOGLE_CLOUD_PROJECT"
          valueFrom:
            configMapKeyRef:
              key: "GOOGLE_CLOUD_PROJECT"
              name: "people-config-e4n3"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "people-hpa-bgze"
  namespace: "default"
  labels:
    app: "people"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "people"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
